---
logging_level: debug
lan:
  iface: eth0
pro6:
  password: control
  host_search:
    - titan
    - warrior
    - Administrators-Mac-mini
    - Administrators-Mac-mini-2
osc:
  disabled: false
  list_id: 38
  mac_addr: 00:1c:42:92:61:aa
  # Override the discovery by MAC address and use the listed IP instead
  discovery_override: 192.168.1.88
  port: 7001